<a href="https://colab.research.google.com/github/shriver42/ESAA/blob/%ED%95%84%EC%82%AC-%EA%B3%BC%EC%A0%9C/0308_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

[01] **데이터 핸들링 - 판다스**
- 핵심 개체 : DataFrame</br> 여러 개의 Series로 이루어졌다
- Series : 칼럼이 하나뿐인 데이터 구조체
- Index : 개별 데이터를 *고유하게* 식별하는 key.</br>  Series와 DataFrame은 모두 Index를 key 값으로 가지고 있다.

[02] **판다스 시작 - 파일을 DataFrame 으로 로딩, 기본 API**

In [1]:
import pandas as pd

- 데이터 불러오기
 - read.csv( ) : 콤마(,)를 통해서 필드를 구분한다</br> &nbsp; DataFrame 으로 변환이 가능하다</br> &nbsp;read.csv('name',sep = '\t') 으로도 사용가능함</br> &nbsp;파일이름을 지정해주는 것이 중요하며 실행 파일과 동일한 디렉토리에 있는 파일명을 로딩함
 - read.table( )
 - read_fwf( ) : FIxed Width으로 고정 길이 기반의 칼럼 포맷을 DataFrame으로 로딩하기 위함

- 데이터 프레임 살펴보기
 - pd.read_csv( ) : 파일명 인자로 들어온 파일을 로딩해 DataFrame 객체로 변환한다
  - read_csv( ) 는 별 다른 지정이 없으면 파일 맨 처음 row를 column 명으로 지정
  - 맨 왼쪽의 0,1,2...는 판다스의 Index 값이다
  - DataFrame.head( ) 은 앞의 N개의 데이터만을 보여준다 (Default 는 5개)

In [2]:
from google.colab import drive
drive.mount('/content/drive')
titanic_df = pd.read_csv('/content/drive/MyDrive/titanic/train.csv')
titanic_df.head(3)

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S

In [3]:
print('titanic 변수 type:', type(titanic_df))
titanic_df

titanic 변수 type: <class 'pandas.core.frame.DataFrame'>

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

 - shape 변수를 이용해서 DataFrame의 행과 열의 크기를 알아볼 수 있다
  - (# of rows, # of columns)

In [4]:
print('DataFrame 크기:', titanic_df.shape)

DataFrame 크기: (891, 12)

- info/describe 변수를 이용해서 DataFrame의 다양한 정보들 조회 가능하다

In [5]:
#Info 변수로는 총 데이터 건수와 데이터 타입, Null 건수를 알 수 있다
titanic_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [6]:
#describe 변수는 숫자형 변수의 칼럼별 n-percentile, 평균, 최대,최소 값을 알 수 있다
#count는 Not Null인 데이터 변수를 나타낸다
titanic_df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

- DataFrame의 [ ] 연산자 내부에 칼럼명 입력시,</br> Series 형태로 특정 칼럼 데이터 세트가 반환됨
- value.counts( )를 통해 해당 칼럼값의 유형과 건수 확인 가능</br> 데이터 분포도 확인을 하는데 매우 유용함

In [7]:
value_counts = titanic_df['Pclass'].value_counts()
print(value_counts)

3    491
1    216
2    184
Name: Pclass, dtype: int64

In [8]:
titanic_pclass = titanic_df['Pclass']
print(type(titanic_pclass))

<class 'pandas.core.series.Series'>

- Series = Index + 단 하나의 칼럼
 - valuee_counts( )는 Series 객체에서만 정의 되어 있음 </br>DataFrame 에서는 이 매서드가 없음
  - value_counts( )가 반환하는 데이터도 series 타입이다

In [9]:
titanic_pclass.head()

0    3
1    1
2    3
3    1
4    3
Name: Pclass, dtype: int64

In [10]:
value_counts = titanic_df['Pclass'].value_counts()
print(type(value_counts))
print(value_counts)

<class 'pandas.core.series.Series'>
3    491
1    216
2    184
Name: Pclass, dtype: int64

[03] DataFrame과 리스트,딕셔너리,넘파이 ndarray 상호 변환
 - DataFrame은 나머지와 다르게 칼럼명을 가지고 있음
 - DataFrame 들은 기본적으로 2차원이기에, 2차원 이하의 데이터들만 변환 가능
  - 1차원 기반 형성시, 칼럼이 하나 필요
  - 2차원 기반 형성시, 형태에 따라 필요한 칼럼명 수가 달라짐

In [11]:
#1차원 형태의 리스트와 넘파이 ndarray 부터 변환
import numpy as np

col_name1 = ['col1']
list1 = [1,2,3]
array1 = np.array(list1)
print('array1 shape:', array1.shape)

#리스트를 이용해 DataFrame 생성
df_list1 = pd.DataFrame(list1,columns=col_name1)
print('1차원 리스트로 만든 DataFrame:\n', df_list1)

#넘파이 ndarray를 이용해 DataFrame 생성
df_array1 = pd.DataFrame(array1,columns=col_name1)
print('1차원 ndarray로 만든 DataFrame:\n', df_array1)

array1 shape: (3,)
1차원 리스트로 만든 DataFrame:
    col1
0     1
1     2
2     3
1차원 ndarray로 만든 DataFrame:
    col1
0     1
1     2
2     3

In [12]:
#2차원 list, ndarray 형태를 기반으로 DataFrame 생성

#3개의 칼럼명이 필요함
col_name2 = ['col1','col2','col3']

#2행 x 3열 형태의 리스트와 ndarray 생성한 뒤 이를 DataFrame으로 변환
list2 = [[1,2,3],
         [11,12,13]]
array2 = np.array(list2)
print('array2 shape:', array2.shape)
df_list2 = pd.DataFrame(list2,columns=col_name2)
print('2차원 리스트로 만든 DataFrame:\n:', df_list2)
df_array2 = pd.DataFrame(array2,columns=col_name2)
print('2차원 ndarray로 만든 DataFrame:\n', df_array2)
print(array2)

array2 shape: (2, 3)
2차원 리스트로 만든 DataFrame:
:    col1  col2  col3
0     1     2     3
1    11    12    13
2차원 ndarray로 만든 DataFrame:
    col1  col2  col3
0     1     2     3
1    11    12    13
[[ 1  2  3]
 [11 12 13]]

- 딕셔너리를 기반으로 DataFrame 변환
 - 딕셔너리의 키(key)는 칼럼명으로, 값(value)는 칼럼 데이터로 변환된다.

In [13]:
dict = {'col1':[1,11],'col2':[2,22],'col3':[3,33]}
df_dict = pd.DataFrame(dict)
print('딕셔너리로 만든 DataFrame:\n',df_dict)

딕셔너리로 만든 DataFrame:
    col1  col2  col3
0     1     2     3
1    11    22    33

- DataFrame을 넘파이 ndarray, 리스트, 딕셔너리로 변환하기

In [14]:
#DataFrame을 ndarray로 변환

array3 = df_dict.values
print('df_dict.values 타입:',type(array3),'df_dict.values shape:',array3.shape)
print(array3)

df_dict.values 타입: <class 'numpy.ndarray'> df_dict.values shape: (2, 3)
[[ 1  2  3]
 [11 22 33]]

In [15]:
#DataFrame을 리스트로 변환
list3 = df_dict.values.tolist()
print('df_dict.values.tolist() 타입:', type(list3))
print(list3)
#DataFrame을 딕셔너리로 변환
dict3 = df_dict.to_dict('list')
print('\n df_dict.to_dict() 타입:', type(dict3))
print(dict3)

df_dict.values.tolist() 타입: <class 'list'>
[[1, 2, 3], [11, 22, 33]]

 df_dict.to_dict() 타입: <class 'dict'>
{'col1': [1, 11], 'col2': [2, 22], 'col3': [3, 33]}

[04] DataFrame의 칼럼 데이터 세트 생성과 수정
 - [  ] 연산자를 이용해 쉽게 할 수 있다</br>Ex) NAME['NEW_COLNAM'] = 0
 - DataFrame 내의 기존 칼럼 값 일괄적 업데이트 할 수 있다

In [16]:
titanic_df['Age_0'] = 0
titanic_df.head(3)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Age_0
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,0
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,0
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,0

In [17]:
# 상숫값을 할당해 Series에 모든 데이터 세트에 일괄 적용 가능하다
titanic_df['Age_by_10'] = titanic_df['Age']*10
titanic_df['Family_No'] = titanic_df['SibSp']+titanic_df['Parch']+1
titanic_df.head(3)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Age_0,Age_by_10,Family_No
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,0,220.0,2
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,0,380.0,2
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,0,260.0,1

In [18]:
#기존값에서 일괄적으로 업데이트 하기
titanic_df['Age_by_10'] = titanic_df['Age_by_10'] + 100
titanic_df.head(3)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Age_0,Age_by_10,Family_No
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,0,320.0,2
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,0,480.0,2
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,0,360.0,1

- DataFrame 데이터 삭제
 - drop( ) 매서드 이용함
 - DataFrame.drop
 (**labels=None**,**axis=0**,index=None,colums=none,level=None,**inplace=False**,errors='raise')
 - axis = 0 : row 축 방향으로 드롭 수행하겠다는 것</br>
   axis = 1 : column 축 방향으로 드롭을 수행하겠다는 것</br> Ex) 이상치 데이터를 제거 하는 경우 말고는 주로 칼럼을 만들고 삭제한다
 - labels에 오는 값 = 인덱스로 간주
 - inplace = False (default) : 자기 자신의 DataFrame의 데이터는 삭제하지 않는다. 삭제된 결과 DataFrame만 반환한다</br> inplace = True : 자신의 DataFrame의 데이터를 삭제한다

In [19]:
#Column 삭제하기

titanic_drop_df = titanic_df.drop('Age_0',axis=1)
titanic_drop_df.head(3)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Age_by_10,Family_No
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,320.0,2
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,480.0,2
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,360.0,1

In [20]:
titanic_df.head(3)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Age_0,Age_by_10,Family_No
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,0,320.0,2
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,0,480.0,2
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,0,360.0,1

- 주의 사항</br>
inplace = True 일 때는 반환 값을 다시 자신의 DataFrame으로 받으면 안된다.</br>
아예 객체 변수를 None으로 만들어 버린다

In [21]:
drop_result = titanic_df.drop(['Age_0','Age_by_10','Family_No'], axis=1,inplace=True)
print('inplace=True로 drop 후 변환된 값:', drop_result)
titanic_df.head(3)

inplace=True로 drop 후 변환된 값: None

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S

In [22]:
#Row 삭제하기

pd.set_option('display.width',1000)
pd.set_option('display.max_colwidth',15)
print('#### before axis 0 drop ####')
print(titanic_df.head(3))

titanic_df.drop([0,1,2],axis=0,inplace=True)
print('#### after axis 0 drop ####')
print(titanic_df.head(3))

#### before axis 0 drop ####
   PassengerId  Survived  Pclass            Name     Sex   Age  SibSp  Parch          Ticket     Fare Cabin Embarked
0            1         0       3  Braund, Mr....    male  22.0      1      0       A/5 21171   7.2500   NaN        S
1            2         1       1  Cumings, Mr...  female  38.0      1      0        PC 17599  71.2833   C85        C
2            3         1       3  Heikkinen, ...  female  26.0      0      0  STON/O2. 31...   7.9250   NaN        S
#### after axis 0 drop ####
   PassengerId  Survived  Pclass            Name     Sex   Age  SibSp  Parch  Ticket     Fare Cabin Embarked
3            4         1       1  Futrelle, M...  female  35.0      1      0  113803  53.1000  C123        S
4            5         0       3  Allen, Mr. ...    male  35.0      0      0  373450   8.0500   NaN        S
5            6         0       3  Moran, Mr. ...    male   NaN      0      0  330877   8.4583   NaN        Q

[05] Index 객체
 - RDBMS의 PK 처럼 레코드를 고유하게 식별하는 객체이다
 - DataFrrame.index / Series.index 속성을 통해 가능

In [23]:
#원본 파일 다시 로딩
titanic_df = pd.read_csv('/content/drive/MyDrive/titanic/train.csv')

#Index 객체 추출
indexes = titanic_df.index
print(indexes)

# Index 객체를 실제 값 arrray로 변환
print('Index 객체 array값:\n',indexes.values)

RangeIndex(start=0, stop=891, step=1)
Index 객체 array값:
 [  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125
 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143
 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161
 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179
 180 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197
 198 199 200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215
 216 217 218 219 220 221 222 223 224 225 226 227 228 229 230 231 232 233
 234 235 236 237 238 239 240 241 242 243 244 245 246 247 248 249 250 251
 252 253 254 255 256 257 258 259 260 261 262 263 264 265 266 267 268 269
 270 271 272 273 274 275 276 277 278 279 280 281 282 283 284 285 286 287
 288 289 290 291 292 293 294 295 296 297 298 299 300 301 302 303 304 305
 306 307 308 309 310 311 312 313 314 315 316 317 318 319 320 321 322 323
 324 325 326 327 328 329 330 331 332 333 334 335 336 337 338 339 340 341
 342 343 344 345 346 347 348 349 350 351 352 353 354 355 356 357 358 359
 360 361 362 363 364 365 366 367 368 369 370 371 372 373 374 375 376 377
 378 379 380 381 382 383 384 385 386 387 388 389 390 391 392 393 394 395
 396 397 398 399 400 401 402 403 404 405 406 407 408 409 410 411 412 413
 414 415 416 417 418 419 420 421 422 423 424 425 426 427 428 429 430 431
 432 433 434 435 436 437 438 439 440 441 442 443 444 445 446 447 448 449
 450 451 452 453 454 455 456 457 458 459 460 461 462 463 464 465 466 467
 468 469 470 471 472 473 474 475 476 477 478 479 480 481 482 483 484 485
 486 487 488 489 490 491 492 493 494 495 496 497 498 499 500 501 502 503
 504 505 506 507 508 509 510 511 512 513 514 515 516 517 518 519 520 521
 522 523 524 525 526 527 528 529 530 531 532 533 534 535 536 537 538 539
 540 541 542 543 544 545 546 547 548 549 550 551 552 553 554 555 556 557
 558 559 560 561 562 563 564 565 566 567 568 569 570 571 572 573 574 575
 576 577 578 579 580 581 582 583 584 585 586 587 588 589 590 591 592 593
 594 595 596 597 598 599 600 601 602 603 604 605 606 607 608 609 610 611
 612 613 614 615 616 617 618 619 620 621 622 623 624 625 626 627 628 629
 630 631 632 633 634 635 636 637 638 639 640 641 642 643 644 645 646 647
 648 649 650 651 652 653 654 655 656 657 658 659 660 661 662 663 664 665
 666 667 668 669 670 671 672 673 674 675 676 677 678 679 680 681 682 683
 684 685 686 687 688 689 690 691 692 693 694 695 696 697 698 699 700 701
 702 703 704 705 706 707 708 709 710 711 712 713 714 715 716 717 718 719
 720 721 722 723 724 725 726 727 728 729 730 731 732 733 734 735 736 737
 738 739 740 741 742 743 744 745 746 747 748 749 750 751 752 753 754 755
 756 757 758 759 760 761 762 763 764 765 766 767 768 769 770 771 772 773
 774 775 776 777 778 779 780 781 782 783 784 785 786 787 788 789 790 791
 792 793 794 795 796 797 798 799 800 801 802 803 804 805 806 807 808 809
 810 811 812 813 814 815 816 817 818 819 820 821 822 823 824 825 826 827
 828 829 830 831 832 833 834 835 836 837 838 839 840 841 842 843 844 845
 846 847 848 849 850 851 852 853 854 855 856 857 858 859 860 861 862 863
 864 865 866 867 868 869 870 871 872 873 874 875 876 877 878 879 880 881
 882 883 884 885 886 887 888 889 890]

- 단일 값 반환 및 슬라이싱이 가능
- Index 객체는 함부로 변환이 불가능함

In [24]:
print(type(indexes.values))
print(indexes.values.shape)
print(indexes[:5].values)
print(indexes.values[:5])
print(indexes[6])

<class 'numpy.ndarray'>
(891,)
[0 1 2 3 4]
[0 1 2 3 4]
6

In [25]:
#index 객체 변경 불가능
indexes[0] = 5

TypeError: Index does not support mutable operations

- Index 연산에서 제외됩니다.</br> 식별용으로만 사용됩니다

In [26]:
series_fair = titanic_df['Fare']
print('Fair Series max 값:', series_fair.max())
print('Fair Series sum 값:', series_fair.sum())
print('sum() Fair Series:', sum(series_fair))
print('Fair Series + 3:\n',(series_fair + 3).head(3) )

Fair Series max 값: 512.3292
Fair Series sum 값: 28693.9493
sum() Fair Series: 28693.949299999967
Fair Series + 3:
 0    10.2500
1    74.2833
2    10.9250
Name: Fare, dtype: float64

- rest_index( ) : 새롭게 인덱스를 연속 숫자 형으로 할당하며 기존 인덱스는 'index' 라는 새로운 칼럼 명으로 추가함
- int 숫자형 데이터가 아닐 경우, 이를 연속 int 숫자형 데이터로 만들 때 사용함
- drop=True 설정 시, 기존 인덱스는 새로운 칼럼에 추가 되지 않고 삭제된다

In [27]:
titanic_reset_df = titanic_df.reset_index(inplace=False)
titanic_reset_df.head(3)

   index  PassengerId  Survived  Pclass            Name     Sex   Age  SibSp  Parch          Ticket     Fare Cabin Embarked
0      0            1         0       3  Braund, Mr....    male  22.0      1      0       A/5 21171   7.2500   NaN        S
1      1            2         1       1  Cumings, Mr...  female  38.0      1      0        PC 17599  71.2833   C85        C
2      2            3         1       3  Heikkinen, ...  female  26.0      0      0  STON/O2. 31...   7.9250   NaN        S

In [28]:
print('### before reset_index ###')
value_counts = titanic_df['Pclass'].value_counts() #Pclass 고유값이 인덱스 역할을 함
print(value_counts)
print('value_counts 객체 변수 타입:',type(value_counts))

new_value_counts = value_counts.reset_index(inplace=False)
print('### After reset_index ###')
print(new_value_counts)
print('new_value_counts 객체 변수 타입:',type(new_value_counts))

### before reset_index ###
3    491
1    216
2    184
Name: Pclass, dtype: int64
value_counts 객체 변수 타입: <class 'pandas.core.series.Series'>
### After reset_index ###
   index  Pclass
0      3     491
1      1     216
2      2     184
new_value_counts 객체 변수 타입: <class 'pandas.core.frame.DataFrame'>

[06] 데이터 셀렉션 및 필터링
 -  넘파이의 인덱싱과 같은 점도, 다른 점도 존재함
 - ix[ ]. iloc[ ], loc[ ] 연산자를 통해 작업을 수행함
 - DataFrame의 [ ]연산자
  - '[ ]' 안에는 칼럼명의 문자 또는 리스트, 인덱스로 변환 가능한 표현식만 가능하다

In [29]:
print('단일 컬럼 데이터 추출:\n', titanic_df[ 'Pclass' ].head(3))
print('\n여러 컬럼들의 데이터 추출:\n', titanic_df[ ['Survived', 'Pclass'] ].head(3))
print('[ ] 안에 숫자 index는 KeyError 오류 발생:\n', titanic_df[0])

단일 컬럼 데이터 추출:
 0    3
1    1
2    3
Name: Pclass, dtype: int64

여러 컬럼들의 데이터 추출:
    Survived  Pclass
0         0       3
1         1       1
2         1       3

KeyError: 0

- 슬라이싱을 하면 원하는 결과 반영 가능하다</br>
CF) titanic_df[0] 칼럼 이름에 0이 없기 때문에 에러가 뜬다

In [30]:
titanic_df[0:2]

   PassengerId  Survived  Pclass            Name     Sex   Age  SibSp  Parch     Ticket     Fare Cabin Embarked
0            1         0       3  Braund, Mr....    male  22.0      1      0  A/5 21171   7.2500   NaN        S
1            2         1       1  Cumings, Mr...  female  38.0      1      0   PC 17599  71.2833   C85        C

- 불린(Boolean) 인덱싱도 표현이 가능하다

In [31]:
titanic_df[ titanic_df['Pclass'] == 3].head(3)

   PassengerId  Survived  Pclass            Name     Sex   Age  SibSp  Parch          Ticket   Fare Cabin Embarked
0            1         0       3  Braund, Mr....    male  22.0      1      0       A/5 21171  7.250   NaN        S
2            3         1       3  Heikkinen, ...  female  26.0      0      0  STON/O2. 31...  7.925   NaN        S
4            5         0       3  Allen, Mr. ...    male  35.0      0      0          373450  8.050   NaN        S

- DataFrame 뒤의 [  ] 연산자의 입력 인자의 혼돈을 방지 하기 위한 가이드
 - DataFrame 바로 뒤의 [  ] 연산자는 넘파이/Series의 [  ]와 다르다
 - DataFrame 바로 뒤의 [  ] 내 입력 값은 칼럼 지정 연산 또는 불린 인덱스 용도로만 사용해야 함
 - DataFrame[0:2]와 같은 슬라이싱 연산으로 데이터 추출하는 방법은 사용하지 않는 개 좋음

- DataFrame의 ix[ ] 연산자
 - ix[# row,# colum] : 위치 기반 인덱싱
 - ix[# row, name of column] : 명칭 기반 인덱싱
 - 현재는 판다스에서 사라지게 됨</br>

In [60]:
data = {'Name': ['Chulmin', 'Eunkyung','Jinwoong','Soobeom'],
        'Year': [2011, 2016, 2015, 2015],
        'Gender': ['Male', 'Female', 'Male', 'Male']
       }
data_df = pd.DataFrame(data, index=['one','two','three','four'])
data_df

           Name  Year  Gender
one     Chulmin  2011    Male
two    Eunkyung  2016  Female
three  Jinwoong  2015    Male
four    Soobeom  2015    Male

- 명칭 기반 인덱싱 vs 위치 기반 인덱싱
 - 행 위치의 인덱스 값과 위치 기반 인덱싱이 integer 형일 떄, 코드 작성에 혼선 초래

In [61]:
#data_df를 rest_index( )로 새로운 숫자형 인덱스를 생성
data_df_reset = data_df.reset_index()
data_df_reset = data_df_reset.rename(columns={'index':'old_index'})
print(data_df_reset)

#인덱스값에 1을 더해서 1부터 시작하는 새로운 인덱스값 생성
data_df_reset.index = data_df_reset.index+1
data_df_reset

  old_index      Name  Year  Gender
0       one   Chulmin  2011    Male
1       two  Eunkyung  2016  Female
2     three  Jinwoong  2015    Male
3      four   Soobeom  2015    Male

  old_index      Name  Year  Gender
1       one   Chulmin  2011    Male
2       two  Eunkyung  2016  Female
3     three  Jinwoong  2015    Male
4      four   Soobeom  2015    Male

In [62]:
data_df_reset.ix[1,1]

AttributeError: 'DataFrame' object has no attribute 'ix'

- DataFrame iloc[ ] 연산자
 - 위치 기반 인덱싱만 허용한다
 - 행 위치에 문자열 인덱스 입력시, 오류 발생
 - 슬라이싱과 팬시 인덱싱은 제공하나 불린 인덱싱은 제공 하지 않는다

In [63]:
data_df.iloc[0,0]

'Chulmin'

In [64]:
# 다음 코드는 오류를 발생시킵니다.
data_df.iloc[0, 'Name']

ValueError: Location based indexing can only have [integer, integer slice (START point is INCLUDED, END point is EXCLUDED), listlike of integers, boolean array] types

In [65]:
data_df_reset.iloc[0,1]

'Chulmin'

- DataFrame loc[ ] 연산자
 - 명칭 기반으로 데이터 추출
 - 행 위치 : DataFrame 인덱스 값</br>
   열 위치 : column 명 입력
 - ' : ' 슬라이싱 할 때, 시작 값~ 끝 값(포함) 주의! </br>
    명칭 기반 인덱싱 이기에 (끝 값-1) 할 수 없다

In [69]:
data_df.loc['one','Name']
data_df_reset.loc[1,'Name'] # 행의 인덱스 값이 정수이기에

'Chulmin'

In [66]:
# 다음 코드는 오류를 발생합니다.
data_df.iloc['one', 0]

ValueError: Location based indexing can only have [integer, integer slice (START point is INCLUDED, END point is EXCLUDED), listlike of integers, boolean array] types

In [75]:
print('위치기반 iloc slicing\n', data_df.iloc[0:1, 0],'\n') #위치 기반 슬라이싱은 (끝값  = 끝 입력값-1 )
print('명칭기반 loc slicing\n', data_df.loc['one':'two', 'Name']) #명칭 기반 슬라이싱은 (끝값 = 끝 입력값)

위치기반 iloc slicing
 one    Chulmin
Name: Name, dtype: object

명칭기반 loc slicing
 one     Chulmin
two    Eunkyung
Name: Name, dtype: object

In [76]:
print(data_df_reset.loc[1:2,'Name']) # 명칭 기반 인덱싱이기에

1     Chulmin
2    Eunkyung
Name: Name, dtype: object

- 불린 인덱싱
 - 불린 인덱싱 적용 후 반환 되는 객체는 DataFrame 이다
 - and 조건: & </br>
   or 조건 : | </br>
   Not 조건 : ~

In [78]:
titanic_df = pd.read_csv('/content/drive/MyDrive/titanic/train.csv')
titanic_boolean = titanic_df[titanic_df['Age'] > 60]
print(type(titanic_boolean))
titanic_boolean

<class 'pandas.core.frame.DataFrame'>

     PassengerId  Survived  Pclass            Name     Sex   Age  SibSp  Parch       Ticket      Fare        Cabin Embarked
33            34         0       2  Wheadon, Mr...    male  66.0      0      0   C.A. 24579   10.5000          NaN        S
54            55         0       1  Ostby, Mr. ...    male  65.0      0      1       113509   61.9792          B30        C
96            97         0       1  Goldschmidt...    male  71.0      0      0     PC 17754   34.6542           A5        C
116          117         0       3  Connors, Mr...    male  70.5      0      0       370369    7.7500          NaN        Q
170          171         0       1  Van der hoe...    male  61.0      0      0       111240   33.5000          B19        S
252          253         0       1  Stead, Mr. ...    male  62.0      0      0       113514   26.5500          C87        S
275          276         1       1  Andrews, Mi...  female  63.0      1      0        13502   77.9583           D7        S
280          281         0       3  Duane, Mr. ...    male  65.0      0      0       336439    7.7500          NaN        Q
326          327         0       3  Nysveen, Mr...    male  61.0      0      0       345364    6.2375          NaN        S
438          439         0       1  Fortune, Mr...    male  64.0      1      4        19950  263.0000  C23 C25 C27        S
456          457         0       1  Millet, Mr....    male  65.0      0      0        13509   26.5500          E38        S
483          484         1       3  Turkula, Mr...  female  63.0      0      0         4134    9.5875          NaN        S
493          494         0       1  Artagaveyti...    male  71.0      0      0     PC 17609   49.5042          NaN        C
545          546         0       1  Nicholson, ...    male  64.0      0      0          693   26.0000          NaN        S
555          556         0       1  Wright, Mr....    male  62.0      0      0       113807   26.5500          NaN        S
570          571         1       2  Harris, Mr....    male  62.0      0      0  S.W./PP 752   10.5000          NaN        S
625          626         0       1  Sutton, Mr....    male  61.0      0      0        36963   32.3208          D50        S
630          631         1       1  Barkworth, ...    male  80.0      0      0        27042   30.0000          A23        S
672          673         0       2  Mitchell, M...    male  70.0      0      0   C.A. 24580   10.5000          NaN        S
745          746         0       1  Crosby, Cap...    male  70.0      1      1    WE/P 5735   71.0000          B22        S
829          830         1       1  Stone, Mrs....  female  62.0      0      0       113572   80.0000          B28      NaN
851          852         0       3  Svensson, M...    male  74.0      0      0       347060    7.7750          NaN        S

In [80]:
titanic_df[titanic_df['Age']>60][['Name','Age']].head (3)

              Name   Age
33  Wheadon, Mr...  66.0
54  Ostby, Mr. ...  65.0
96  Goldschmidt...  71.0

In [82]:
titanic_df.loc[titanic_df['Age']>60,['Name','Age']].head(3)

              Name   Age
33  Wheadon, Mr...  66.0
54  Ostby, Mr. ...  65.0
96  Goldschmidt...  71.0

In [84]:
titanic_df[(titanic_df['Age']>60)&(titanic_df['Pclass']==1)&(titanic_df['Sex']=='female')]

     PassengerId  Survived  Pclass            Name     Sex   Age  SibSp  Parch  Ticket     Fare Cabin Embarked
275          276         1       1  Andrews, Mi...  female  63.0      1      0   13502  77.9583    D7        S
829          830         1       1  Stone, Mrs....  female  62.0      0      0  113572  80.0000   B28      NaN

In [86]:
#개별 조건 할당 후 변수 결합하여 불린 인덱싱 수행
cond1 = titanic_df['Age']>60
cond2 = titanic_df['Pclass'] == 1
cond3 = titanic_df['Sex'] == 'female'
titanic_df[cond1&cond2&cond3]

     PassengerId  Survived  Pclass            Name     Sex   Age  SibSp  Parch  Ticket     Fare Cabin Embarked
275          276         1       1  Andrews, Mi...  female  63.0      1      0   13502  77.9583    D7        S
829          830         1       1  Stone, Mrs....  female  62.0      0      0  113572  80.0000   B28      NaN

[07] 정렬, Aggregation 함수, GroupBy 적용
 - DataFrame, Series 정렬 - sort_values( )
  - 주요 파라미터는 by, ascending, inplace
  - ascending = True : 오름차순 / ascending = False : 내림차순
  - 기존의 DataFrame은 그대로 유지하며 정렬된 DataFrame 결과를 반환한다 (inplace = False : default)

In [87]:
#오름차순 정리
titanic_sorted = titanic_df.sort_values(by=['Name'])
titanic_sorted.head(3)

     PassengerId  Survived  Pclass            Name     Sex   Age  SibSp  Parch     Ticket   Fare Cabin Embarked
845          846         0       3  Abbing, Mr....    male  42.0      0      0  C.A. 5547   7.55   NaN        S
746          747         0       3  Abbott, Mr....    male  16.0      1      1  C.A. 2673  20.25   NaN        S
279          280         1       3  Abbott, Mrs...  female  35.0      1      1  C.A. 2673  20.25   NaN        S

In [89]:
#내림차순 정리
titanic_sorted = titanic_df.sort_values(by=['Pclass','Name'],ascending=False)
titanic_sorted.head(3)

     PassengerId  Survived  Pclass            Name   Sex   Age  SibSp  Parch    Ticket  Fare Cabin Embarked
868          869         0       3  van Melkebe...  male   NaN      0      0    345777   9.5   NaN        S
153          154         0       3  van Billiar...  male  40.5      0      2  A/5. 851  14.5   NaN        S
282          283         0       3  de Pelsmaek...  male  16.0      0      0    345778   9.5   NaN        S

- Aggregation 함수 적용
 - 모든 칼럼에 해당 aggregation을 적용함

In [92]:
titanic_df.count()

PassengerId    891
Survived       891
Pclass         891
Name           891
Sex            891
Age            714
SibSp          891
Parch          891
Ticket         891
Fare           891
Cabin          204
Embarked       889
dtype: int64

In [94]:
titanic_df[['Age',"Fare"]].mean ()

Age     29.699118
Fare    32.204208
dtype: float64

- group_by( ) 적용
 - by에 칼럼을 입력하면, 칼럼 별로 group by 가 된다
 - 결과는 DataFrameGroupBy 라는 또 다른 형태로 반환한다
 - groupby() 결과에 aggregation 함수를 호출하면,</br>groupby() 대상 칼럼을 제외한 모든 칼럼에 해당 agrregation 함수를 적용한다.
 - agg() 내에 입력 값으로 딕셔너리 형태로 aggregation이 적용될 칼럼들과 함수를 입력한다

In [95]:
titanic_groupby = titanic_df.groupby(by='Pclass')
print(type(titanic_groupby))

<class 'pandas.core.groupby.generic.DataFrameGroupBy'>

In [96]:
#groupby() 한 Pcalss 제외하고 다 count 함수가 적용되었다
titanic_groupby = titanic_df.groupby('Pclass').count()
titanic_groupby

        PassengerId  Survived  Name  Sex  Age  SibSp  Parch  Ticket  Fare  Cabin  Embarked
Pclass
1               216       216   216  216  186    216    216     216   216    176       214
2               184       184   184  184  173    184    184     184   184     16       184
3               491       491   491  491  355    491    491     491   491     12       491

In [100]:
#특정 칼럼들을 기준으로 aggregation 진행
titanic_groupby = titanic_df.groupby('Pclass')[['PassengerId', 'Survived']].count()
titanic_groupby

        PassengerId  Survived
Pclass
1               216       216
2               184       184
3               491       491

In [103]:
titanic_df.groupby('Pclass')['Age'].agg([max, min])

         max   min
Pclass
1       80.0  0.92
2       70.0  0.67
3       74.0  0.42

In [104]:
agg_format={'Age':'max', 'SibSp':'sum', 'Fare':'mean'}
titanic_df.groupby('Pclass').agg(agg_format)

         Age  SibSp       Fare
Pclass
1       80.0     90  84.154687
2       70.0     74  20.662183
3       74.0    302  13.675550

[08] 결손 데이터 처리하기
 - NULL 인 경우를 의미함(cf.넘파이의 NaN)
 - isna() 로 결손 데이터 여부 확인하기
  - isna().sum() 호출 시, True=1, False=0 으로 변환 됨
 - fillna()로 missing data 대체하기
  - fillna() 이용해 반환값으로 아예 추가하고 싶으면, inplace=True 설정 필요</br> 또는 반환 값을 기존 값과 같다고 놓아 덮어씌워야함

In [106]:
titanic_df.isna().head(3)

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [107]:
titanic_df.isna().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [108]:
titanic_df['Cabin'] = titanic_df['Cabin'].fillna('C000')
titanic_df.head(3)

   PassengerId  Survived  Pclass            Name     Sex   Age  SibSp  Parch          Ticket     Fare Cabin Embarked
0            1         0       3  Braund, Mr....    male  22.0      1      0       A/5 21171   7.2500  C000        S
1            2         1       1  Cumings, Mr...  female  38.0      1      0        PC 17599  71.2833   C85        C
2            3         1       3  Heikkinen, ...  female  26.0      0      0  STON/O2. 31...   7.9250  C000        S

In [109]:
titanic_df['Age'] = titanic_df['Age'].fillna(titanic_df['Age'].mean())
titanic_df['Embarked'] = titanic_df['Embarked'].fillna('S')
titanic_df.isna().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Cabin          0
Embarked       0
dtype: int64

[09] apply lambda 식으로 데이터 가공
 - lambda 식은 파이썬에서 함수형 프로그래밍을 지원하기 위해서 만들었다
 - ' : ' 의 왼쪽에 있는 x는 입력인자, 오른쪽은 입력 인자의 계산식(=반환 값)이다
 - 여러 개의 값을 입력 인자로 사용해야 할 경우는 map() 함수를 결합해서 사용한다

In [110]:
#몇 가지 예시
def get_square(a):
  return a**2

print('3의 제곱은:', get_square(3))

3의 제곱은: 9

In [ ]:
#위의 예시를 lambda 식으로 변형 했을 때

In [111]:
lambda_square = lambda x : x ** 2
print('3의 제곱은:',lambda_square(3))

3의 제곱은: 9

In [112]:
a=[1,2,3]
squares = map(lambda x : x**2, a)
list(squares)

[1, 4, 9]

In [113]:
#apply에 lambda식을 적용해 가공하기
titanic_df['Name_len']= titanic_df['Name'].apply(lambda x : len(x))
titanic_df[['Name','Name_len']].head(3)

             Name  Name_len
0  Braund, Mr....        23
1  Cumings, Mr...        51
2  Heikkinen, ...        22

- lambda 식에서 if 절 사용시 주의점
 - if 식보다 반환 값을 앞에 기술해야 함</br>
  ex) lambda x : if x <=15 'Child' else 'Adult' (X)</br>
      lambad x : 'Child' if x<=15 else 'Adult' (O)

In [114]:
#나이가 15세 미만이면 'Child', 그렇지 않으면 'Adult' 구분
titanic_df['Child_Adult'] = titanic_df['Age'].apply(lambda x : 'Child' if x <=15 else 'Adult' )
titanic_df[['Age','Child_Adult']].head(8)

         Age Child_Adult
0  22.000000       Adult
1  38.000000       Adult
2  26.000000       Adult
3  35.000000       Adult
4  35.000000       Adult
5  29.699118       Adult
6  54.000000       Adult
7   2.000000       Child

- if 와 else 만 지원하고 else if 는 지원하지 않는다.</br> else if 를 이용하려면 else절에 또 다른 else절을 내포해야 한다
- 이 역시도 반환 값이 식보다 먼저 나왔음

In [ ]:
#15세 이하면 Child, 16~60은 Adult 아니면 Elderly로 분류
titanic_df['Age_cat'] = titanic_df['Age'].apply(lambda x : 'Child' if x<=15 else ('Adult' if x <= 60 else
                                                                                  'Elderly'))
titanic_df['Age_cat'].value_counts()

In [115]:
# 나이에 따라 세분화된 분류를 수행하는 함수 생성.
def get_category(age):
    cat = ''
    if age <= 5: cat = 'Baby'
    elif age <= 12: cat = 'Child'
    elif age <= 18: cat = 'Teenager'
    elif age <= 25: cat = 'Student'
    elif age <= 35: cat = 'Young Adult'
    elif age <= 60: cat = 'Adult'
    else : cat = 'Elderly'

    return cat

# lambda 식에 위에서 생성한 get_category( ) 함수를 반환값으로 지정.
# get_category(X)는 입력값으로 ‘Age’ 컬럼 값을 받아서 해당하는 cat 반환
titanic_df['Age_cat'] = titanic_df['Age'].apply(lambda x : get_category(x))
titanic_df[['Age','Age_cat']].head()

    Age      Age_cat
0  22.0      Student
1  38.0        Adult
2  26.0  Young Adult
3  35.0  Young Adult
4  35.0  Young Adult